<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class OpdSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $models = array(
            array('name' => 'Sekretariat Daerah', 'email' => 'setda@probolinggokota.go.id'),
            array('name' => 'Bagian Hukum', 'email' => 'bagianhukum@probolinggokota.go.id'),
            array('name' => 'Bagian Kesejahteraan Rakyat', 'email' => 'bagiankesra@probolinggokota.go.id'),
            array('name' => 'Bagian Keuangan dan Sarana Prasarana', 'email' => 'bagiankeuangansarpras@probolinggokota.go.id'),
            array('name' => 'Bagian Organisasi', 'email' => 'bagianorganisasi@probolinggokota.go.id'),
            array('name' => 'Bagian Pemerintahan', 'email' => 'bagianpemerintahan@probolinggokota.go.id'),
            array('name' => 'Bagian Pengadaan Barang dan Jasa', 'email' => 'bagianpengadaanbarangjasa@probolinggokota.go.id'),
            array('name' => 'Bagian Perekonomian dan Pembangunan', 'email' => 'bagianperekonomianpembangunan@probolinggokota.go.id'),
            array('name' => 'Bagian Umum', 'email' => 'bagianumum@probolinggokota.go.id'),
            array('name' => 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia', 'email' => 'bkpsdm@probolinggokota.go.id'),
            array('name' => 'Badan Kesatuan Bangsa dan Politik', 'email' => 'bakesbangpol@probolinggokota.go.id'),
            array('name' => 'Badan Penanggulangan Bencana Daerah', 'email' => 'bpbd@probolinggokota.go.id'),
            array('name' => 'Badan Pendapatan, Pengelolaan Keuangan dan Aset', 'email' => 'bppkad@probolinggokota.go.id'),
            array('name' => 'Badan Perencanaan Pembangunan Daerah dan Litbang', 'email' => 'bappedalitbang@probolinggokota.go.id'),
            array('name' => 'Dinas Kepemudaan, Olah Raga dan Pariwisata', 'email' => 'dispopar@probolinggokota.go.id'),
            array('name' => 'Dinas Kependudukan dan Pencatatan Sipil', 'email' => 'dispendukcapil@probolinggokota.go.id'),
            array('name' => 'Dinas Kesehatan, Pengendalian Penduduk dan Keluarga Berencana', 'email' => 'dkppkb@probolinggokota.go.id'),
            array('name' => 'UOBK RSUD dr. Moch. Saleh', 'email' => 'uobkrsuddrmochsaleh@probolinggokota.go.id'),
            array('name' => 'UPTD Puskesmas Jati', 'email' => 'puskesmasjati@probolinggokota.go.id'),
            array('name' => 'UPTD Puskesmas Kanigaran', 'email' => 'puskesmaskanigaran@probolinggokota.go.id'),
            array('name' => 'UPTD Puskesmas Kedopok', 'email' => 'puskesmaskedopok@probolinggokota.go.id'),
            array('name' => 'UPTD Puskesmas Ketapang', 'email' => 'puskemasketapang@probolinggokota.go.id'),
            array('name' => 'UPTD Puskesmas Sukabumi', 'email' => 'puskesmassukabumi@probolinggokota.go.id'),
            array('name' => 'UPTD Puskesmas Wonoasih', 'email' => 'puskesmaswonoasih@probolinggokota.go.id'),
            array('name' => 'UPTD Laboratorium Kesehatan dan Lingkungan', 'email' => 'uptdlabkesehatanlingkungan@probolinggokota.go.id'),
            array('name' => 'Dinas Koperasi, Usaha Mikro, Perdagangan dan Perindustrian', 'email' => 'dkupp@probolinggokota.go.id'),
            array('name' => 'UPTD Pasar', 'email' => 'uptdpasar@probolinggokota.go.id'),
            array('name' => 'Dinas Lingkungan Hidup', 'email' => 'dlh@probolinggokota.go.id'),
            array('name' => 'UPTD Informasi dan Pendidikan Lingkungan Hidup', 'email' => 'uptdinformasiplh@probolinggokota.go.id'),
            array('name' => 'UPTD Pengolahan Sampah', 'email' => 'uptpengolahansampah@probolinggokota.go.id'),
            array('name' => 'UPTD Laboratorium Lingkungan', 'email' => 'uptlablingkungan@probolinggokota.go.id'),
            array('name' => 'Dinas Penanamen Modal, Pelayanan Terpadu Satu Pintu dan Tenaga Kerja', 'email' => 'dpmptspnaker@probolinggokota.go.id'),
            array('name' => 'Dinas Pendidikan dan Kebudayaan', 'email' => 'disdikbud@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Curahgrinting 1', 'email' => 'sdncurahgrinting1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Curahgrinting 3', 'email' => 'sdncurahgrinting3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Jati 1', 'email' => 'sdnjati1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Jati 4', 'email' => 'sdnjati4@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Jrebeng Kidul', 'email' => 'sdnjrebengkidul@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Jrebeng Kulon 1', 'email' => 'sdnjrebengkulon1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Jrebeng Kulon 2', 'email' => 'sdnjrebengkulon2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Jrebeng Lor 1', 'email' => 'sdnjrebenglor1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Jrebeng Lor 3', 'email' => 'sdnjrebenglor3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Jrebeng Lor 7', 'email' => 'sdnjrebenglor7@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Jrebeng Wetan', 'email' => 'sdnjrebengwetan@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kademangan 1', 'email' => 'sdnkademangan1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kademangan 2', 'email' => 'sdnkademangan2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kademangan 4', 'email' => 'sdnkademangan4@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kanigaran 1', 'email' => 'sdnkanigaran1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kanigaran 3', 'email' => 'sdnkanigaran3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kanigaran 6', 'email' => 'sdnkanigaran6@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kareng Lor 1', 'email' => 'sdnkarenglor1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kareng Lor 2', 'email' => 'sdnkarenglor2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kebonsari Kulon 1', 'email' => 'sdnkebonsarikulon1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kebonsari Kulon 3', 'email' => 'sdnkebonsarikulon3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kebonsari Kulon 6', 'email' => 'sdnkebonsarikulon6@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kebonsari Wetan 1', 'email' => 'sdnkebonsariwetan1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kebonsari Wetan 3', 'email' => 'sdnkebonsariwetan3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kedopok 1', 'email' => 'sdnkedopok1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kedopok 2', 'email' => 'sdnkedopok2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kedungasem 1', 'email' => 'sdnkedungasem1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kedungasem 4', 'email' => 'sdnkedungasem4@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Kedunggaleng', 'email' => 'sdnkedunggaleng@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Ketapang 1', 'email' => 'sdnketapang1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Ketapang 2', 'email' => 'sdnketapang2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Ketapang 3', 'email' => 'sdnketapang3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mangunharjo 1', 'email' => 'sdnmangunharjo1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mangunharjo 10', 'email' => 'sdnmangunharjo10@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mangunharjo 12', 'email' => 'sdnmangunharjo12@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mangunharjo 2', 'email' => 'sdnmangunharjo2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mangunharjo 4', 'email' => 'sdnmangunharjo4@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mangunharjo 5', 'email' => 'sdnmangunharjo5@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mangunharjo 6', 'email' => 'sdnmangunharjo6@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mangunharjo 7', 'email' => 'sdnmangunharjo7@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mayangan 1', 'email' => 'sdnmayangan1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mayangan 2', 'email' => 'sdnmayangan2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Mayangan 4', 'email' => 'sdnmayangan4@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Pakistaji 1', 'email' => 'sdnpakistaji1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Pakistaji 2', 'email' => 'sdnpakistaji2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Pilang 1', 'email' => 'sdnpilang1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Pilang 2', 'email' => 'sdnpilang2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Pilang 3', 'email' => 'sdnpilang3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Pohsangit Kidul 1', 'email' => 'sdnpohsangitkidul1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Pohsangit Kidul 2', 'email' => 'sdnpohsangitkidul2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sukabumi 1', 'email' => 'sdnsukabumi1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sukabumi 10', 'email' => 'sdnsukabumi10@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sukabumi 2', 'email' => 'sdnsukabumi2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sukabumi 4', 'email' => 'sdnsukabumi4@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sukabumi 6', 'email' => 'sdnsukabumi6@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sukabumi 7', 'email' => 'sdnsukabumi7@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sukoharjo 1', 'email' => 'sdnsukoharjo1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sukoharjo 3', 'email' => 'sdnsukoharjo3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sukoharjo 4', 'email' => 'sdnsukoharjo4@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sumber Taman 1', 'email' => 'sdnsumbertaman1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sumber Taman 2', 'email' => 'sdnsumbertaman2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sumber Wetan 1', 'email' => 'sdnsumberwetan1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Sumber Wetan 2', 'email' => 'sdnsumberwetan2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Tisnonegaran 1', 'email' => 'sdntisnonegaran1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Tisnonegaran 3', 'email' => 'sdntisnonegaran3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Triwung Kidul 1', 'email' => 'sdntriwungkidul1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Triwung Kidul 2', 'email' => 'sdntriwungkidul2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Triwung Kidul 3', 'email' => 'sdntriwungkidul3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Triwung Lor 1', 'email' => 'sdntriwunglor1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Triwung Lor 2', 'email' => 'sdntriwunglor2@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Triwung Lor 3', 'email' => 'sdntriwunglor3@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Wiroborang 1', 'email' => 'sdnwiroborang1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Wiroborang 4', 'email' => 'sdnwiroborang4@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Wonoasih 1', 'email' => 'sdnwonoasih1@probolinggokota.go.id'),
            array('name' => 'Sekolah Dasar Negeri Wonoasih 2', 'email' => 'sdnwonoasih2@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 1', 'email' => 'smpn1@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 10', 'email' => 'smpn10@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 2', 'email' => 'smpn2@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 3', 'email' => 'smpn3@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 4', 'email' => 'smpn4@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 5', 'email' => 'smpn5@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 6', 'email' => 'smpn6@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 7', 'email' => 'smpn7@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 8', 'email' => 'smpn8@probolinggokota.go.id'),
            array('name' => 'Sekolah Menengah Pertama Negeri 9', 'email' => 'smpn9@probolinggokota.go.id'),
            array('name' => 'Dinas Perhubungan', 'email' => 'dishub@probolinggokota.go.id'),
            array('name' => 'UPTD Pengujian Kendaraan Bermotor', 'email' => 'uptdpkb@probolinggokota.go.id'),
            array('name' => 'Dinas Perpustakaan dan Kearsipan', 'email' => 'disperpusip@probolinggokota.go.id'),
            array('name' => 'Dinas Pertanian, Ketahanan Pangan dan Perikanan', 'email' => 'dpkpp@probolinggokota.go.id'),
            array('name' => 'UPTD Rumah Potong Hewan', 'email' => 'uptdrph@probolinggokota.go.id'),
            array('name' => 'UPTD Tempat Pelelangan Ikan', 'email' => 'utpdtpi@probolinggokota.go.id'),
            array('name' => 'UPTD Pengembangan Mutu dan Pemasaran Hasil Perikanan', 'email' => 'uptdpmphp@probolinggokota.go.id'),
            array('name' => 'Dinas PUPR dan Perkim', 'email' => 'dpuperkim@probolinggokota.go.id'),
            array('name' => 'Dinas Sosial, Pemberdayaan Perempuan dan Perlindungan Anak', 'email' => 'dinsosp3a@probolinggokota.go.id'),
            array('name' => 'Inspektorat', 'email' => 'inspektorat@probolinggokota.go.id'),
            array('name' => 'Satuan Polisi Pamong Praja', 'email' => 'satpolpp@probolinggokota.go.id'),
            array('name' => 'Sekretariat DPRD', 'email' => 'sekretariatdprd@probolinggokota.go.id'),
            array('name' => 'Kecamatan Kademangan ', 'email' => 'keckademangan@probolinggokota.go.id'),
            array('name' => 'Kelurahan Kademangan', 'email' => 'kelkademangan@probolinggokota.go.id'),
            array('name' => 'Kelurahan Ketapang', 'email' => 'kelketapang@probolinggokota.go.id'),
            array('name' => 'Kelurahan Pilang', 'email' => 'kelpilang@probolinggokota.go.id'),
            array('name' => 'Kelurahan Pohsangit Kidul', 'email' => 'kelpohsangitkidul@probolinggokota.go.id'),
            array('name' => 'Kelurahan Triwung Kidul', 'email' => 'keltriwungkidul@probolinggokota.go.id'),
            array('name' => 'Kelurahan Triwung Lor', 'email' => 'keltriwunglor@probolinggokota.go.id'),
            array('name' => 'Kecamatan Kanigaran', 'email' => 'keckanigaran@probolinggokota.go.id'),
            array('name' => 'Kelurahan Curah Grinting', 'email' => 'kelcurahgrinting@probolinggokota.go.id'),
            array('name' => 'Kelurahan Kanigaran', 'email' => 'kelkanigaran@probolinggokota.go.id'),
            array('name' => 'Kelurahan Kebonsari Kulon', 'email' => 'kelkebonsarikulon@probolinggokota.go.id'),
            array('name' => 'Kelurahan Kebonsari Wetan', 'email' => 'kelkebonsariwetan@probolinggokota.go.id'),
            array('name' => 'Kelurahan Sukoharjo', 'email' => 'kelsukoharjo@probolinggokota.go.id'),
            array('name' => 'Kelurahan Tisnonegaran', 'email' => 'keltisnonegaran@probolinggokota.go.id'),
            array('name' => 'Kecamatan Kedopok', 'email' => 'keckedopok@probolinggokota.go.id'),
            array('name' => 'Kelurahan Jrebeng Kulon', 'email' => 'keljrebengkulon@probolinggokota.go.id'),
            array('name' => 'Kelurahan Jrebeng Lor', 'email' => 'keljrebenglor@probolinggokota.go.id'),
            array('name' => 'Kelurahan Jrebeng Wetan', 'email' => 'keljrebengwetan@probolinggokota.go.id'),
            array('name' => 'Kelurahan Kareng Lor', 'email' => 'kelkarenglor@probolinggokota.go.id'),
            array('name' => 'Kelurahan Kedopok', 'email' => 'kelkedopok@probolinggokota.go.id'),
            array('name' => 'Kelurahan Sumber Wetan', 'email' => 'kelsumberwetan@probolinggokota.go.id'),
            array('name' => 'Kecamatan Mayangan', 'email' => 'kecmayangan@probolinggokota.go.id'),
            array('name' => 'Kelurahan Jati', 'email' => 'keljati@probolinggokota.go.id'),
            array('name' => 'Kelurahan Mangunharjo', 'email' => 'kelmangunharjo@probolinggokota.go.id'),
            array('name' => 'Kelurahan Mayangan', 'email' => 'kelmayangan@probolinggokota.go.id'),
            array('name' => 'Kelurahan Sukabumi', 'email' => 'kelsukabumi@probolinggokota.go.id'),
            array('name' => 'Kelurahan Wiroborang', 'email' => 'kelwiroborang@probolinggokota.go.id'),
            array('name' => 'Kecamatan Wonoasih', 'email' => 'kecwonoasih@probolinggokota.go.id'),
            array('name' => 'Kelurahan Jrebeng Kidul', 'email' => 'keljrebengkidul@probolinggokota.go.id'),
            array('name' => 'Kelurahan Kedungasem', 'email' => 'kelkedungasem@probolinggokota.go.id'),
            array('name' => 'Kelurahan Kedunggaleng', 'email' => 'kelkedunggaleng@probolinggokota.go.id'),
            array('name' => 'Kelurahan Pakistaji', 'email' => 'kelpakistaji@probolinggokota.go.id'),
            array('name' => 'Kelurahan Sumber Taman', 'email' => 'kelsumbertaman@probolinggokota.go.id'),
            array('name' => 'Kelurahan Wonoasih', 'email' => 'kelwonoasih@probolinggokota.go.id'),
        );
        DB::table('opd')->insert($models);
    }
}
